/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Handler.KurvHandler;
import Model.Ret;
import Model.VareLine;
import util.numberutil;

/**
 *
 * @author Mark
 */
public class Print extends javax.swing.JPanel {

    private KurvHandler kh;
    private numberutil nb;
    /**
     * Creates new form JPanel
     */
    public Print() {
        kh = KurvHandler.getInstance();
        nb = new numberutil();
        this.setSize(500, 715);
        initComponents();
        addTekst();
    }
    
    public void addTekst(){
        jTextArea1.setText("");
        int cost = 0;
        int antalDage = 0;
        jTextArea1.append("Retter: \n");
        for (Ret ret : kh.getRetList()) {
            jTextArea1.append(ret.getRetNavn()+ "\n");
            cost = cost + ret.getTotalPris();
            antalDage = antalDage + ret.getAntalDage();
        }
        jTextArea1.append("\n");
        jTextArea1.append("Vare: \n");
        for (VareLine vl : kh.getVareLine()) {
            int count = vl.getVare().getVareNavn().length();
            jTextArea1.append(vl.getVare().getVareNavn());
            while(count < 25){
                jTextArea1.append(" ");
                count++;
            }
            if (vl.getVare().getVareNavn().length() < 6) {
                jTextArea1.append("\t");
            }
            jTextArea1.append("\t " + vl.getVareAntal() + "X \n");
        }
        jTextArea1.append("\n");
        jTextArea1.append("Total Pris: "+nb.getpris(kh.getTotalPris()) + " \tAntal Dage: "+kh.getAntalDageRetter()+"\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jButton1.setText("Print");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
