/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Handler.NyRetHandler;
import Handler.VareHandler;
import Model.Ret;
import Model.RetType;
import Model.Vare;
import Model.VareGruppe;
import Model.VareLine;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import util.Listeners;
import util.numberutil;

/**
 *
 * @author Mark
 */
public class TilføjNyRet extends javax.swing.JPanel implements ActionListener {

    private boolean editRet;
    private Listeners l;
    private NyRetHandler nrh;
    private VareHandler vh;
    private numberutil nb;

    /**
     * Creates new form TilføjNyRet
     */
    public TilføjNyRet(boolean editRet) {

        this.editRet = editRet;
        this.l = Listeners.getList();
        l.addListener(this);
        this.nrh = NyRetHandler.getInstance();
        this.vh = VareHandler.getInstance();
        this.nb = new numberutil();

        initComponents();

        if (!editRet) {
            setComboBoxRetOGVareGruppe();
        } else {
            showRetter();
        }
    }
    
    public void showRetter(){
        jC_retType.removeAllItems();
        jC_VareGruppe.removeAllItems();
        for (Ret ret : vh.getAllRetter()) {
            jC_retType.addItem(ret.getRetNavn());
        }
        for (VareGruppe vg : vh.getVareGruppe()) {
            jC_VareGruppe.addItem(vg.getNavn());
        }
    }
    
    public void showRet(){
        Ret retten = null;
        for (Ret ret : vh.getAllRetter()) {
            if (ret.getRetNavn().equals(jC_retType.getSelectedItem().toString())) {
                jT_retNavn.setText(ret.getRetNavn());
                jT_AntalDage.setText(ret.getAntalDage()+"");
                retten = ret;
            }
        }
        editTilføjVare(retten);
    }

    public void setComboBoxRetOGVareGruppe() {
        jC_VareGruppe.removeAllItems();
        jC_retType.removeAllItems();
        for (RetType rt : vh.getRetType()) {
            jC_retType.addItem(rt.getType());
        }
        for (VareGruppe vg : vh.getVareGruppe()) {
            jC_VareGruppe.addItem(vg.getNavn());
        }
    }

    public void visVare() {
        int GruppeId = 0;
        jC_Vare.removeAllItems();
        for (VareGruppe vg : vh.getVareGruppe()) {
            if (vg.getNavn().equals(jC_VareGruppe.getSelectedItem().toString())) {
                GruppeId = vg.getId();
            }
        }
        for (Vare v : nrh.getChoosenVare(GruppeId)) {
            jC_Vare.addItem(v.getVareNavn());
        }
    }

    public void setVareLine() {
        VAreLine line;
        jPanel1.removeAll();
        for (int i = 0; i < nrh.getVareLine().size(); i++) {
            line = new VAreLine(nrh.getVareLine().get(i), editRet);
            jPanel1.add(line);
            line.setLocation(0, ((5 * i) + (line.getHeight() * i)));
            line.setVisible(true);
            int count = i + 1;
            jPanel1.setPreferredSize(new Dimension(line.getWidth(), ((5 * count) + (line.getHeight() * count))));
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    public void editTilføjVare(Ret retten){
        nrh.removeVarelineComplite();
        
        for (VareLine vLine : retten.getVareList()) {
           nrh.addProduktString(vLine.getVare().getVareNavn()); 
        }
        setVareLine();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jC_retType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jT_retNavn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jT_AntalDage = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jC_VareGruppe = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jC_Vare = new javax.swing.JComboBox();
        jB_Tilføj = new javax.swing.JButton();
        jB_Gemret = new javax.swing.JButton();
        jL_TotalPris = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jLabel1.setText("Ret Type");

        jC_retType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_retTypeActionPerformed(evt);
            }
        });

        jLabel2.setText("Ret Navn");

        jLabel3.setText("Antal Dage");

        jLabel4.setText("Vare Gruppe");

        jC_VareGruppe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC_VareGruppeActionPerformed(evt);
            }
        });

        jLabel5.setText("Vare");

        jB_Tilføj.setText("Tilføj Vare");
        jB_Tilføj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_TilføjActionPerformed(evt);
            }
        });

        jB_Gemret.setText("Gem Ret");
        jB_Gemret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_GemretActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jL_TotalPris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jC_retType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_retNavn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jT_AntalDage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jC_VareGruppe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jC_Vare, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Tilføj, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Gemret, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jC_retType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jT_retNavn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jT_AntalDage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jC_VareGruppe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jC_Vare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jB_Tilføj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_TotalPris, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jB_Gemret, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jC_VareGruppeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_VareGruppeActionPerformed
        visVare();
    }//GEN-LAST:event_jC_VareGruppeActionPerformed

    private void jB_TilføjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_TilføjActionPerformed
        nrh.addProduktString(jC_Vare.getSelectedItem().toString());
    }//GEN-LAST:event_jB_TilføjActionPerformed

    private void jB_GemretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_GemretActionPerformed
        if (!editRet) {
            if (!jT_AntalDage.getText().equals("")) {
                if (!jT_retNavn.getText().equals("")) {
                    nrh.addRet(jT_retNavn.getText(), Integer.parseInt(jT_AntalDage.getText()), jC_retType.getSelectedItem().toString());
                }
            }
        }
    }//GEN-LAST:event_jB_GemretActionPerformed

    private void jC_retTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC_retTypeActionPerformed
        if (editRet) {
            showRet();
        }
    }//GEN-LAST:event_jC_retTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Gemret;
    private javax.swing.JButton jB_Tilføj;
    private javax.swing.JComboBox jC_Vare;
    private javax.swing.JComboBox jC_VareGruppe;
    private javax.swing.JComboBox jC_retType;
    private javax.swing.JLabel jL_TotalPris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_AntalDage;
    private javax.swing.JTextField jT_retNavn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        switch (ae.getActionCommand()) {
            case "Update Ny Ret":
                setVareLine();
                jL_TotalPris.setText("Total Pris: " + nb.getpris(nrh.getPris()));
                break;

        }
    }
}
